# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "17cffb931cb453cd24c5732b3ce81974"
name = "Kentro"
application_url = "https://us-central1-kentro-last-mile.cloudfunctions.net/shopifyOAuthStart"
embedded = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://us-central1-kentro-last-mile.cloudfunctions.net/shopifyComplianceWebhook"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://us-central1-kentro-last-mile.cloudfunctions.net/shopifyOAuthCallback"
]
